---

- name: Install requirements
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - curl
    - gnupg
    - debian-archive-keyring
    - apt-transport-https
    - openssh-server
    - ca-certificates

- name: Gitlab apt key
  apt_key:
    url: https://packages.gitlab.com/gitlab/gitlab-ce/gpgkey

- name: Gitlab apt repository
  apt_repository:
    repo: "deb https://packages.gitlab.com/gitlab/gitlab-ce/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main"
    update_cache: yes
    state: present

- name: Install gitlab
  no_log: "{{ gitlab_skip_sysctl_setup }}"
  apt:
    pkg: gitlab-ce
    state: latest
    dpkg_options: "{{ 'force-unsafe-io' if gitlab_dpkg_unsafe_io else omit }}"
  environment:
    EXTERNAL_URL: "{{ gitlab_url }}"
  ignore_errors: "{{ gitlab_skip_sysctl_setup }}"

- name: Configure gitlab
  template:
    src: "{{ gitlab_config_template }}"
    dest: /etc/gitlab/gitlab.rb
  notify: Reconfigure gitlab

- name: Patch install script for sysctl
  replace:
    replace: '    command "cat /etc/sysctl.conf"'
    regexp: '^    command \"cat /etc/sysctl.conf /etc/sysctl\.d/\*\.conf  | sysctl -e -p -\"$'
    path: /opt/gitlab/embedded/cookbooks/package/resources/sysctl.rb
  when: gitlab_skip_sysctl_setup
  notify: Reconfigure gitlab

- name: Letsencrypt cron
  cron:
    name: auto renew letsencrypt certificates
    minute: 1
    hour: 23
    weekday: 0
    job: '/usr/bin/gitlab-ctl renew-le-certs'
  when: gitlab_letsencrypt
